---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  site/content/project:
    default_front_matter_template: project
  site/content/post:
    default_front_matter_template: post
upload_dir: site//static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
