baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "GrumpyCorp Heavy Industries"

enableEmoji = true

[params]
    author = "Robin Giese"
    description = "-add description here-"
    githubUsername = "rgiese"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

##
## Configure menu
##

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Sidebar

[[menu.icon]]
    url = "mailto:robin@grumpycorp.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rgiese/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/robingiese"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.imdb.com/name/nm8515322/?ref_=fn_al_nm_1"
    name = "fab fa-imdb"
    weight = 4