baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "GrumpyCorp"

enableEmoji = true

[params]
    author = "Robin Giese"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
